### ISSUE TITLE
Dot source syntax gets clobbered

### ISSUE THREAD

**Issue by n8v** [DTW-DanWard/PowerShell-Beautifier#13]
I have Pester scripts which dot-source another file in the current dir,
```powershell
. .\File.ps1
```

Edit-DTWBeautifyScript turns this into the very broken
```powershell
..\File.ps1
```

I see the test case stuff and will try to work on a failing test shortly, maybe even a fix

**Comment by n8v** [comment]
Not sure I'm smart enough to fix the actual problem but it seems to be at https://github.com/DTW-DanWard/PowerShell-Beautifier/blob/master/src/DTW.PS.Beautifier.Main.psm1#L979 ... the nuance is that the dot operator for properties like `$File.Name` has different rules from the dot source operator `. File.ps1`

**Comment by DTW-DanWard** [comment]
That code that determines whether or not a space should be added is *not* pretty... I have a ticket for rewriting it.  Once I check out the tokens being generated a solution should become available.  I should be able to look into these issues this afternoon.

**Comment by DTW-DanWard** [comment]
Yeah, that code is not pretty, but thankfully is commented well.  I added a specific case for writing a space for Operator '.' followed by a Command.  Committing shortly.
