### ISSUE TITLE
Automate local testing for PowerShell Core in Docker containers

### ISSUE THREAD

**Issue by DTW-DanWard** [DTW-DanWard/PowerShell-Beautifier#19]

**Comment by nschonni** [comment]
Alternately or additionally, you could setup CI with https://travis-ci.org/ for Ubuntu and OSX testing, and https://www.appveyor.com/ for the Windows testing

**Comment by DTW-DanWard** [comment]
@nschonni That's definitely on my roadmap!  I wanted to get the local Docker tests working first as it's best for quick feature branch testing.

**Comment by DTW-DanWard** [comment]
Current version of Invoke-RunTestScriptInDockerCoreContainers.ps1 is ready to roll.  Possible enhancements, will create as tickets.
