### ISSUE TITLE
Revisit initial whitespace inside @( groupings

### ISSUE THREAD

**Issue by DTW-DanWard** [DTW-DanWard/PowerShell-Beautifier#23]
If arrays are tight with whitespace (no space after commas), does it make sense to have a space after the @( opening? Even if @( is followed by a newline, no need for space.  Add more grouping examples and test.

**Comment by m-kostrzewa** [comment]
I don't like the space after @(, here's PR that changes it: https://github.com/DTW-DanWard/PowerShell-Beautifier/issues/23
