### ISSUE TITLE
Setup PowerShell Gallery publishing

### ISSUE THREAD

**Issue by nschonni** [DTW-DanWard/PowerShell-Beautifier#27]
It would be a nice-to-have since that allows installation through `Install-Module`

https://github.com/Microsoft/ReportingServicesTools has an example of setting up CI to push to the gallery on Git tags

**Comment by DTW-DanWard** [comment]
Also on my roadmap.  Thanks for that link, that will save me a lot of time!

**Comment by DTW-DanWard** [comment]
Note to myself: also check out posh-docker; simpler setup.

**Comment by DTW-DanWard** [comment]
PowerShell-Beautifier is in the PowerShell Gallery: https://www.powershellgallery.com/packages/PowerShell-Beautifier/1.2.5
I've automated the publishing process locally; still need to automate CI...
