### ISSUE TITLE
Parametersets, implicit to explicit request

### ISSUE THREAD

**Issue by TheIncorrigible1** [DTW-DanWard/PowerShell-Beautifier#32]
Hello,
Are there any plans to clean implicit parameter sets? e.g.

```powershell
gci /tmp/ex -> Get-ChildItem -Path '/tmp/ex'
```

**Comment by DTW-DanWard** [comment]
Yep!  It's a larger, more complicated change so it's on the roadmap but there isn't an explicit issue for it.

**Comment by DTW-DanWard** [comment]
Closing this for now, needs to be done with V2 of utility.
