### ISSUE TITLE
External command parameters borked by ValidCommandParameterNames

### ISSUE THREAD

**Issue by m-kostrzewa** [DTW-DanWard/PowerShell-Beautifier#42]
During experiments, snippet
```
docker run -id blabla
```
was changed to
```
docker run -Id
```
I presume that `-Id` is a learned `CommandParameter` and is stored in `ValidCommandParameterNames` table. However, maybe it shouldn't be applied for parameters of external commands? Not sure how to fix it though. We would need to detect whether we're inside powershell or an external command. 

Slightly related https://github.com/DTW-DanWard/PowerShell-Beautifier/issues/41

**Comment by DTW-DanWard** [comment]
Yep, you've hit upon some of the limitations with the current implementation.  Right now the replacement logic is not very smart - for example it can't easily tell PowerShell parameters versus those for external commands.  I do have a plan for fixing this but it involves a complete re-write and using abstract syntax trees.  I've started on this work but it is going to be a _long_ process; I don't expect a beta version for many months.  The plus side: it will have some crazy awesome functionality (not just whitespace cleanup and simple text casing fixes), will be very configurable and will allow users to write their own rules.

**Comment by DTW-DanWard** [comment]
Closing this for now; will be addressed (hopefully) in next-gen version.
