### ISSUE TITLE
Add option to change the indent size

### ISSUE THREAD

**Issue by samjviana** [DTW-DanWard/PowerShell-Beautifier#50]
It would be nice to be able to change that, personally speaking i prefer using 4 whitespaces as indent with whitespace

**Comment by DTW-DanWard** [comment]
By default it formats with 2 spaces but you can have it format with 4 spaces or tab characters.  Specify the `IndentType` parameter:
```
Edit-DTWBeautifyScript -SourcePath C:\temp\File1.ps1 -IndentType Tabs
Edit-DTWBeautifyScript -SourcePath C:\temp\File1.ps1 -IndentType FourSpaces

```
