### ISSUE TITLE
Does this run the file in any way? 

### ISSUE THREAD

**Issue by dadbaud** [DTW-DanWard/PowerShell-Beautifier#68]
Quite possibly an ignorant Q, and I do apologize for submitting it as an issue - im new to GitHub as an account holder and wasnt sure if there were comments for repo projects. 

Does this run the PS script in any sense? I would assume not, but would like to use this to clean up obfuscated code when dealing with malware, and cant risk it running!

TIA

**Comment by DTW-DanWard** [comment]
Nope, it doesn't run the script.  However it does entirely re-write it from scratch and I can't guarantee that it can handle every situation, so make sure you have a backup of the file, that you've committed it first, etc.
