### ISSUE TITLE
Support PowerShell Core

### ISSUE THREAD

**Issue by DTW-DanWard** [DTW-DanWard/PowerShell-Beautifier#7]
Expect these changes:
* OS-specific line endings, provide parameter to override environment (in case Windows user wants Unix line endings and vice-versa).
* Changes to better support Linux default file encoding? If a file doesn't appear to have any Unicode, assume it is UTF-8-sans BOM?
* Change for OS-specific temp file location?  Or keep in same folder as script?
* Any API changes?  Any cmdlet changes?

**Comment by n8v** [comment]
Here's an example of the errors it emits for me in Core on MacOS:

```
> $IsOSX                                                                                                   
True

> $PSVersionTable                                                                                          

Name                           Value                                                                                                  
----                           -----                                                                                                  
PSVersion                      6.0.0-alpha                                                                                            
PSEdition                      Core                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                
BuildVersion                   3.0.0.0                                                                                                
GitCommitId                    v6.0.0-alpha.15                                                                                        
CLRVersion                                                                                                                            
WSManStackVersion              3.0                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                    
SerializationVersion           1.1.0.1      

> Edit-DTWBeautifyScript ./_generate_tagindex.ps1                                                          

Get-Command : The term 'Get-ComputerInfo' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:112 char:15
+       while ((Get-Command -Name $Cmd).CommandType -eq 'Alias') { $Cmd ...
+               ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ComputerInfo:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
 
The property 'CommandType' cannot be found on this object. Verify that the property exists.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:112 char:14
+       while ((Get-Command -Name $Cmd).CommandType -eq 'Alias') { $Cmd ...
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
Get-Command : The term 'Get-Service' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:112 char:15
+       while ((Get-Command -Name $Cmd).CommandType -eq 'Alias') { $Cmd ...
+               ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-Service:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
 
The property 'CommandType' cannot be found on this object. Verify that the property exists.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:112 char:14
+       while ((Get-Command -Name $Cmd).CommandType -eq 'Alias') { $Cmd ...
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
Get-Command : The term 'Start-Service' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:112 char:15
+       while ((Get-Command -Name $Cmd).CommandType -eq 'Alias') { $Cmd ...
+               ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Start-Service:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
 
The property 'CommandType' cannot be found on this object. Verify that the property exists.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:112 char:14
+       while ((Get-Command -Name $Cmd).CommandType -eq 'Alias') { $Cmd ...
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
Get-Command : The term 'Stop-Service' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:112 char:15
+       while ((Get-Command -Name $Cmd).CommandType -eq 'Alias') { $Cmd ...
+               ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Stop-Service:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
 
The property 'CommandType' cannot be found on this object. Verify that the property exists.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:112 char:14
+       while ((Get-Command -Name $Cmd).CommandType -eq 'Alias') { $Cmd ...
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
Get-Item : Cannot bind argument to parameter 'Path' because it is null.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:271 char:24
+        (Get-Item -Path $env:TEMP),`
+                        ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetItemCommand
 
Get-Member : 
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:275 char:13
+       ($_ | Get-Member).Name;
+             ~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
 
The property 'Name' cannot be found on this object. Verify that the property exists.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:275 char:7
+       ($_ | Get-Member).Name;
+       ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
Get-Member : 
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:276 char:13
+       ($_ | Get-Member -Static).Name;
+             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
 
The property 'Name' cannot be found on this object. Verify that the property exists.
At /Users/nathan/PowerShell-Beautifier/src/DTW.PS.Beautifier.PopulateValidNames.psm1:276 char:7
+       ($_ | Get-Member -Static).Name;
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
```

**Comment by DTW-DanWard** [comment]
@n8v Interesting... this is super helpful!  Some of these seem to be PowerShell commands (or environment variables) not ported to Core yet, or perhaps given a different name.  It'll require some research into Core and a few tweaks I'm sure.  I will look more into this once I complete features #1 and #2 - possible as soon as this weekend.

**Comment by DTW-DanWard** [comment]
Hey @n8v 
I started working on Core support. Unfortunately I don't have a Mac to test on so I'll need you to test a few commands on your local machine. 

First off - I notice you are running an alpha version of Core, can you upgrade to the latest (v6.0.0-beta.2) copy?  Some of the errors in your post look like certain cmdlets the beautifier uses don't exist in your Core instance but do exist on my Windows beta 2 copy. Definitely the *-Service commands [weren't supported yet on macOS in alpha.15](https://github.com/PowerShell/PowerShell/blob/v6.0.0-alpha.15/docs/KNOWNISSUES.md) - see Command Availability. Maybe you can try these tests before and after you upgrade:

1. Get-Member exists?
```
Get-Command Get-Member
```
Does that return the Cmdlet Get-Member?


2. Need a better preexisting folder path than env:TEMP
env:TEMP is failing for you; that makes sense as that's Windows-specific.  Do these two commands return True for you?
```
Test-Path variable:PsHome
Test-Path $PsHome
```

Once I get feedback on these issues I will make some changes and push them to a issue branch for you that you can download and test.

**Comment by n8v** [comment]
On Sun, Jun 18, 2017 at 7:58 AM, Dan Ward <notifications@github.com> wrote:

> Hey @n8v <https://github.com/n8v>
> I started working on Core support. Unfortunately I don't have a Mac to
> test on so I'll need you to test a few commands on your local machine.
>
> First off - I notice you are running an alpha version of Core, can you
> upgrade to the latest (v6.0.0-beta.2) copy? Some of the errors in your post
> look like certain cmdlets the beautifier uses don't exist in your Core
> instance but do exist on my Windows beta 2 copy. Definitely the *-Service
> commands weren't supported yet on macOS in alpha.15
> <https://github.com/PowerShell/PowerShell/blob/v6.0.0-alpha.15/docs/KNOWNISSUES.md>
> - see Command Availability. Maybe you can try these tests before and after
> you upgrade:
>
>    1. Get-Member exists?
>
> Get-Command Get-Member
>
> Does that return the Cmdlet Get-Member?
>


Yes `Get-Member` totally exists and is working fine on most commands.

Executing the code in `Initialize-ValidMemberNames` a line at a time shows
that the reference to nonexistent `$Env:TEMP` on line 271 breaks the array
definition, screwing everything else up. If I remove that line, the other
types work just fine.



>
>    1. Need a better preexisting folder path than env:TEMP
>    env:TEMP is failing for you; that makes sense as that's
>    Windows-specific. Do these two commands return True for you?
>
> Test-Path variable:PsHome
> Test-Path $PsHome
>
> Once I get feedback on these issues I will make some changes and push them
> to a issue branch for you that you can download and test.
>
>
>
Both return True on Core 6.0.0-alpha ... I will get and use latest
powershell for any further discussion though.

**Comment by n8v** [comment]
Cool! A lot of the other errors go away with 6.0.0-beta -- the weird thing with -alpha was that aliases like `gsv` existed for cmdlets like `Get-Service` that did not exist. With that one reference to $env:TEMP commented out, I'm getting great results with no errors on a few files.

**Comment by DTW-DanWard** [comment]
Excellent!  I will change the $env:TEMP to $PSHOME.  I also have one more code change (use environment-specific instead of Windows-style line-endings).  The code changes will be fast - changing documentation will take longer - but I should have a new version up in an hour or so; I'll let you know.  

Thanks for helping out with the testing!

**Comment by DTW-DanWard** [comment]
Hey @n8v  Sorry, this took a little bit longer than I thought (bug with using MD5 hashes for before/after file comparison in Core, alas) but it's now ready for testing.  Pull/download the latest master and give it a try.  If it's working for you I'll give the Atom-Beautify folks a heads up that we are ready/close for integration.

**Comment by n8v** [comment]
@DTW-DanWard it works great now, thanks! I think it's ready to support Core and ready for more testing... I just found a bug which I'll open separately

**Comment by n8v** [comment]
I ran the test cases and found weird Core behavior in Alias.ps1, which gets beautified,

```powershell
Get-ChildItem c:\temp

ls c:\temp

Get-Item c:\temp\asdf.txt

Get-Content c:\temp\asdf.txt

cat c:\temp\asdf.txt

Remove-Item c:\temp\asdf.txt

write "asdf"

Get-ChildItem -Filter *.txt | sort LastWriteTime

Get-ChildItem | Where-Object { $_.Extension -eq '.txt' }

Get-ChildItem | ForEach-Object { write $_.Name }
```

The reason is that `ls` `cat` and `write` aliases aren't present in Core since they are expected to refer to native OS binaries.

Again, not sure really how best to handle that. I guess it's not that weird for `ls` to be an alias on Windows and a native thing on Mac/Linux... but I think in context, a Mac user beautifying a PowerShell script would expect it to get de-aliased the same as on Windows.

So maybe special handling for the few that aren't in Core?

$winaliases|?{$_ -NotIn $corealiases}|sort                                                     
```
ac     
asnp   
cat    
compare
cp     
cpp    
curl   
diff   
epsn   
gsnp   
gsv    
gwmi   
ipsn   
ise    
iwmi   
lp     
ls     
man    
mount  
mv     
npssc  
ogv    
ps     
rm     
rmdir  
rsnp   
rujb   
rwmi   
sasv   
shcm   
sleep  
sort   
spsv   
start  
sujb   
swmi   
tee    
trcm   
wget   
write 
```

or, ` gc .\diffaliases.txt|get-alias|%{"'$($_.name)' = '$($_.definition)'"}`

```powershell
@{
'ac' = 'Add-Content'
'asnp' = 'Add-PSSnapIn'
'cat' = 'Get-Content'
'compare' = 'Compare-Object'
'cp' = 'Copy-Item'
'cpp' = 'Copy-ItemProperty'
'curl' = 'Invoke-WebRequest'
'diff' = 'Compare-Object'
'epsn' = 'Export-PSSession'
'gsnp' = 'Get-PSSnapIn'
'gsv' = 'Get-Service'
'gwmi' = 'Get-WmiObject'
'ipsn' = 'Import-PSSession'
'ise' = 'powershell_ise.exe'
'iwmi' = 'Invoke-WMIMethod'
'lp' = 'Out-Printer'
'ls' = 'Get-ChildItem'
'man' = 'help'
'mount' = 'New-PSDrive'
'mv' = 'Move-Item'
'npssc' = 'New-PSSessionConfigurationFile'
'ogv' = 'Out-GridView'
'ps' = 'Get-Process'
'rm' = 'Remove-Item'
'rmdir' = 'Remove-Item'
'rsnp' = 'Remove-PSSnapin'
'rujb' = 'Resume-Job'
'rwmi' = 'Remove-WMIObject'
'sasv' = 'Start-Service'
'shcm' = 'Show-Command'
'sleep' = 'Start-Sleep'
'sort' = 'Sort-Object'
'spsv' = 'Stop-Service'
'start' = 'Start-Process'
'sujb' = 'Suspend-Job'
'swmi' = 'Set-WMIInstance'
'tee' = 'Tee-Object'
'trcm' = 'Trace-Command'
'wget' = 'Invoke-WebRequest'
'write' = 'Write-Output'
}
```

**Comment by DTW-DanWard** [comment]
Just making sure, Core on Mac has cmdlets for `Get-ChildItem`, `Get-Content` and `Write-Output` but doesn't have the corresponding `ls` `cat` and `write` aliases?  If so, that's OK, we can manually add some entries to the command lookup table for those values.  It's not a huge deal but you're right -  this is something to keep an eye on when script written on one platform is run on another...

I will create a ticket for adding every existing Windows alias to Alias.ps1.  Running the test script on different platforms will help find these missing aliases in the future - especially as Core is updated.

**Comment by DTW-DanWard** [comment]
@n8v And I will compare your listings above and add the necessary manual entries to the lookup table.

**Comment by n8v** [comment]
Yes, there are actually two different cases:

1. The Alias doesn't exist because it is named like a native binary, e.g. `ps`, `cat`, `ls`, `write`, `sleep`, `ac`, `curl`, but the corresponding commands like `Get-ChildItem`, `Get-Content` and `Write-Output` do exist. I think these are unlikely to change. They're Unixisms sugared in to PowerShell but presumably anybody writing beautifiable PowerShell will expect the PowerShell version. Many work quite differently... it's good to beautify them out of code so it's more explicit which thing is meant.

2. It doesn't exist because the command isn't supported on Core yet, like `Get-WmiObject` or `Start-Service`. It's conceivable these could be implemented in the future? But also correct to beautify them.

**Comment by DTW-DanWard** [comment]
OK, just committed.  Thanks Nathan @n8v for the heads up on this AND the missing mappings; that saved me a lot of time!  Give the latest version a try and let me know how it goes.

I won't close #7 or #15 *just* yet; this weekend I will load a Ubuntu docker instance on my machine to check aliases on that as well to make sure nothing else is missing.  Then I'll tell the Atom-Beautify folks that the PS Beautifier should be ready.

**Comment by DTW-DanWard** [comment]
Hey @n8v 
I think the beautifier needs a different approach to this alias situation.  Currently the beautifier aggregates all aliases across all OSes, whether or not a particular alias exists on the local machine.  This means that for a script originally written on Windows but getting beautified on a Mac, 'curl' would get replaced with 'Invoke-WebRequest', maybe a good thing...?  But if the Mac user had created that script and was running and beautifying it locally, this replacement is a **bad** breaking change for the beautifier to make.

The safest answer is this: by default only aliases known to exist across all platforms (hard-coded list) should get replaced.  This will still cover many of the most frequently used aliases so I'm cool with that - much happier than the thought of breaking someone's code.  I will implement this change now; I'll also remove all the Windows-specific aliases from the test files so running the test script won't cause any issues for non-Windows OSes.

Down the road there could also be an optional parameter -UseLocalAliases that could load up all the aliases from memory on the user's machine instead of using the hard-code list.  This would get OS-specific aliases plus any custom ones the user had.  The user would need to be aware that if they are using this with a script originally written on a different OS that it could cause problems.

FYI - I heard Jeffrey Snover give a talk about Core a few weeks back and apparently aliases across OSes was one of the most contentions that came up during Core design - curl in particular.

**Comment by DTW-DanWard** [comment]
Also, you might want to delete your copy of src/DTW.PS.BeautifierValidValuesCache.txt so it has the correct values (old alias list removed).

**Comment by DTW-DanWard** [comment]
OK @n8v pull latest master, test your scripts and let me know how it goes.  I tested on the Ubuntu docker and it's looking good with the exception of line endings in the test process (this will get fixed with #12).

If this is now working 100% for you I'll contact the Atom-Beautify folks.  I have one more question for them about stdout/err but beyond that it should be ready.

**Comment by DTW-DanWard** [comment]
Closing this; tested most recently on beta 5, all good.

**Comment by n8v** [comment]
Cool, thanks for your work on this! I'm sorry I think I missed your Jun 24 comments when I was out fishing...

**Comment by DTW-DanWard** [comment]
No problem; thanks again for all the help!
